### ISSUE TITLE
Image to pixel conversion

### ISSUE THREAD

**Issue by eravallirao** [macbrennan90/udacity_AIND_P6#1]
Hi,
I was facing issues while converting image into pixels values and dumping it into csv. It is showing that array cannot be converted into (96,96,1) image. Can you please help me with conversion of image into pixels

**Comment by eravallirao** [comment]
Traceback (most recent call last):
  File "train_landmark.py", line 11, in <module>
    X_train, y_train = load_data()
  File "/Users/sukshi/Downloads/facial-keypoint-detection-master/utils.py", line 29, in load_data
    X = np.vstack(df['Image'].values) / 255.  # scale pixel values to [0, 1]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
